### ISSUE TITLE
IsaacGym gets stuck when run play.py

### ISSUE THREAD

**Issue by Ke-Wang1017** [chengxuxin/expressive-humanoid#3]
Hi I followed the steps in **Prepare dataset** section, all steps ran well except the last command `python play.py debug --task h1_view --motion_name motions_autogen_all.yaml`. After I ran this the Isaacgym window pops up but then it is black and frozen. As the screen shots below show:
![Screenshot from 2024-08-13 22-58-07](https://github.com/user-attachments/assets/0c5bd68f-0f6a-4c3d-87f0-8e982d54c75d)
![Screenshot from 2024-08-13 22-58-33](https://github.com/user-attachments/assets/c65b04d2-8ae4-4e1d-9964-ca7356843a70)
It seems it gets stuck on loading the policy, but the policy exists in the `log/debug` folder. 
How can I solve this?

**Comment by dbdxnuliba** [comment]
hello, when I train the h1 ,it shows the error :

FileNotFoundError: [Errno 2] No such file or directory: '/home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/sample00_rep00.npy'

(humanoid) nuli@nuli-Legion-Y9000P-IRX8:~/rl/expressive-humanoid/legged_gym/legged_gym/scripts$ python train.py debug --task h1_view --motion_name motions_debug.yaml --debug
Importing module 'gym_38' (/home/nuli/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/nuli/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 2.4.1+cu121
Device count 1
/home/nuli/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/nuli/.cache/torch_extensions/py38_cu121 as PyTorch extensions root...
Emitting ninja build file /home/nuli/.cache/torch_extensions/py38_cu121/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
2024-09-06 07:19:49,705 - INFO - logger - logger initialized
MOVING MOTION DATA TO GPU, USING CACHE: False
wandb: WARNING Disabling the wandb service is deprecated as of version 0.18.0 and will be removed in version 0.19.0.
Setting seed: 1
******************** Loading motion library ********************
Loading 1/24 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/sample00_rep00.npy
Traceback (most recent call last):
  File "train.py", line 72, in <module>
    train(args)
  File "train.py", line 65, in train
    env, env_cfg = task_registry.make_env(name=args.task, args=args)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/utils/task_registry.py", line 98, in make_env
    env = task_class(   cfg=env_cfg,
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic_view_motion.py", line 18, in __init__
    super().__init__(cfg, sim_params, physics_engine, sim_device, headless)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic_eval.py", line 12, in __init__
    super().__init__(cfg, sim_params, physics_engine, sim_device, headless)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 43, in __init__
    self.init_motions(cfg)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 118, in init_motions
    self._load_motion(motion_file, cfg.motion.no_keybody)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 157, in _load_motion
    self._motion_lib = MotionLib(motion_file=motion_file,
  File "/home/nuli/rl/expressive-humanoid/ASE/ase/utils/motion_lib.py", line 118, in __init__
    self._load_motions(motion_file, no_keybody)
  File "/home/nuli/rl/expressive-humanoid/ASE/ase/utils/motion_lib.py", line 274, in _load_motions
    curr_motion = SkeletonMotion.from_file(curr_file)
  File "/home/nuli/rl/expressive-humanoid/ASE/ase/poselib/poselib/core/backend/abstract.py", line 128, in from_file
    d = np.load(path, allow_pickle=True).item()
  File "/home/nuli/anaconda3/envs/humanoid/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/sample00_rep00.npy'

but I there no file named sample00_rep00.npy under retarget_npy folder
![image](https://github.com/user-attachments/assets/ccf9584e-dee9-463e-9a76-e12204a7d7e5)

so,do you meet such problem ,when train h1, could you please tell me how to get the data named sample00_rep00.npy,thanks

**Comment by Ke-Wang1017** [comment]
> hello, when I train the h1 ,it shows the error :
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/sample00_rep00.npy'
> 
> (humanoid) nuli@nuli-Legion-Y9000P-IRX8:~/rl/expressive-humanoid/legged_gym/legged_gym/scripts$ python train.py debug --task h1_view --motion_name motions_debug.yaml --debug Importing module 'gym_38' (/home/nuli/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so) Setting GYM_USD_PLUG_INFO_PATH to /home/nuli/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json PyTorch version 2.4.1+cu121 Device count 1 /home/nuli/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/src/gymtorch Using /home/nuli/.cache/torch_extensions/py38_cu121 as PyTorch extensions root... Emitting ninja build file /home/nuli/.cache/torch_extensions/py38_cu121/gymtorch/build.ninja... Building extension module gymtorch... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N) ninja: no work to do. Loading extension module gymtorch... 2024-09-06 07:19:49,705 - INFO - logger - logger initialized MOVING MOTION DATA TO GPU, USING CACHE: False wandb: WARNING Disabling the wandb service is deprecated as of version 0.18.0 and will be removed in version 0.19.0. Setting seed: 1 ******************** Loading motion library ******************** Loading 1/24 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/sample00_rep00.npy Traceback (most recent call last): File "train.py", line 72, in train(args) File "train.py", line 65, in train env, env_cfg = task_registry.make_env(name=args.task, args=args) File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/utils/task_registry.py", line 98, in make_env env = task_class( cfg=env_cfg, File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic_view_motion.py", line 18, in **init** super().**init**(cfg, sim_params, physics_engine, sim_device, headless) File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic_eval.py", line 12, in **init** super().**init**(cfg, sim_params, physics_engine, sim_device, headless) File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 43, in **init** self.init_motions(cfg) File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 118, in init_motions self._load_motion(motion_file, cfg.motion.no_keybody) File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 157, in _load_motion self._motion_lib = MotionLib(motion_file=motion_file, File "/home/nuli/rl/expressive-humanoid/ASE/ase/utils/motion_lib.py", line 118, in **init** self._load_motions(motion_file, no_keybody) File "/home/nuli/rl/expressive-humanoid/ASE/ase/utils/motion_lib.py", line 274, in _load_motions curr_motion = SkeletonMotion.from_file(curr_file) File "/home/nuli/rl/expressive-humanoid/ASE/ase/poselib/poselib/core/backend/abstract.py", line 128, in from_file d = np.load(path, allow_pickle=True).item() File "/home/nuli/anaconda3/envs/humanoid/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load fid = stack.enter_context(open(os_fspath(file), "rb")) FileNotFoundError: [Errno 2] No such file or directory: '/home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/sample00_rep00.npy'
> 
> but I there no file named sample00_rep00.npy under retarget_npy folder ![image](https://private-user-images.githubusercontent.com/13350158/364981336-ccf9584e-dee9-463e-9a76-e12204a7d7e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NzQwODYsIm5iZiI6MTcyNTg3Mzc4NiwicGF0aCI6Ii8xMzM1MDE1OC8zNjQ5ODEzMzYtY2NmOTU4NGUtZGVlOS00NjNlLTlhNzYtZTEyMjA0YTdkN2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDA5MjMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMDI1OTk2NWQ4MTgzMGM2YTcyOTkxZTY2MDdhMzFjZTUxYzBjYzg2ZjFlZjQ4MTMzM2M2YjkyOTZjMDA3MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kp1HGEz_dp0nz5E56AVaozNdt6D0Azflv6xHOifFfzU)
> 
> so,do you meet such problem ,when train h1, could you please tell me how to get the data named sample00_rep00.npy,thanks

Hi I also find that there is no `sample00_rep00.npy`, i commented this one out and uses other files

**Comment by AlorithmKing** [comment]
i meet the same error when i run  python train.py debug --task h1_view --motion_name motions_debug.yaml --debug
error: FileNotFoundError: [Errno 2] No such file or directory: xxx.../ASE/ase/poselib/data/retarget_npy/sample00_rep00.npy

**Comment by HaoranZhangumich** [comment]
same issue here

**Comment by fanpeace** [comment]
> Hi I followed the steps in **Prepare dataset** section, all steps ran well except the last command `python play.py debug --task h1_view --motion_name motions_autogen_all.yaml`. After I ran this the Isaacgym window pops up but then it is black and frozen. As the screen shots below show: ![Screenshot from 2024-08-13 22-58-07](https://github.com/user-attachments/assets/0c5bd68f-0f6a-4c3d-87f0-8e982d54c75d) ![Screenshot from 2024-08-13 22-58-33](https://github.com/user-attachments/assets/c65b04d2-8ae4-4e1d-9964-ca7356843a70) It seems it gets stuck on loading the policy, but the policy exists in the `log/debug` folder. How can I solve this?

me too.
