### ISSUE TITLE
when train, can't find sample00_rep00.npy

### ISSUE THREAD

**Issue by dbdxnuliba** [chengxuxin/expressive-humanoid#7]
(humanoid) nuli@nuli-Legion-Y9000P-IRX8:~/rl/expressive-humanoid/legged_gym/legged_gym/scripts$ python train.py debug --task h1_view --motion_name motions_debug.yaml --debug
Importing module 'gym_38' (/home/nuli/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/nuli/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 2.4.1+cu121
Device count 1
/home/nuli/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/nuli/.cache/torch_extensions/py38_cu121 as PyTorch extensions root...
Emitting ninja build file /home/nuli/.cache/torch_extensions/py38_cu121/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
2024-09-06 07:19:49,705 - INFO - logger - logger initialized
MOVING MOTION DATA TO GPU, USING CACHE: False
wandb: WARNING Disabling the wandb service is deprecated as of version 0.18.0 and will be removed in version 0.19.0.
Setting seed: 1
******************** Loading motion library ********************
Loading 1/24 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/sample00_rep00.npy
Traceback (most recent call last):
  File "train.py", line 72, in <module>
    train(args)
  File "train.py", line 65, in train
    env, env_cfg = task_registry.make_env(name=args.task, args=args)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/utils/task_registry.py", line 98, in make_env
    env = task_class(   cfg=env_cfg,
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic_view_motion.py", line 18, in __init__
    super().__init__(cfg, sim_params, physics_engine, sim_device, headless)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic_eval.py", line 12, in __init__
    super().__init__(cfg, sim_params, physics_engine, sim_device, headless)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 43, in __init__
    self.init_motions(cfg)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 118, in init_motions
    self._load_motion(motion_file, cfg.motion.no_keybody)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 157, in _load_motion
    self._motion_lib = MotionLib(motion_file=motion_file,
  File "/home/nuli/rl/expressive-humanoid/ASE/ase/utils/motion_lib.py", line 118, in __init__
    self._load_motions(motion_file, no_keybody)
  File "/home/nuli/rl/expressive-humanoid/ASE/ase/utils/motion_lib.py", line 274, in _load_motions
    curr_motion = SkeletonMotion.from_file(curr_file)
  File "/home/nuli/rl/expressive-humanoid/ASE/ase/poselib/poselib/core/backend/abstract.py", line 128, in from_file
    d = np.load(path, allow_pickle=True).item()
  File "/home/nuli/anaconda3/envs/humanoid/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/sample00_rep00.npy'

And we can only produce npy files like this by the command:
python retarget_motion_h1_all.py
![image](https://github.com/user-attachments/assets/6999f2ab-26f4-41d1-890c-dae5d0382b79)

and how can I produce or get sample00_rep00.npy file,thanks

**Comment by AlorithmKing** [comment]
@dbdxnuliba  have you solve this error

**Comment by dbdxnuliba** [comment]
Sorry, I haven't solved it yet, I've temporarily commented it out.

**Comment by AlorithmKing** [comment]
@dbdxnuliba Agree that I think this is an example of the action library rather than the actual use. I also comment it
 out

**Comment by HaoranZhangumich** [comment]
Hi, @dbdxnuliba I just wanna ask which line did you comment it out?

**Comment by openhe-hub** [comment]
> Hi, [@dbdxnuliba](https://github.com/dbdxnuliba) I just wanna ask which line did you comment it out?

comment 'sample00_rep00' in motions_debug.yaml

**Comment by openhe-hub** [comment]
I also met with this problem, commenting does work
