### ISSUE TITLE
python train.py debug --task h1_view --motion_name motions_debug.yaml --debug RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)  nvrtc compilation failed: 

### ISSUE THREAD

**Issue by dbdxnuliba** [chengxuxin/expressive-humanoid#9]
(humanoid) nuli@nuli:~/rl/expressive-humanoid/legged_gym/legged_gym/scripts$ python train.py debug --task h1_view --motion_name motions_debug.yaml --debug
Importing module 'gym_38' (/home/nuli/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/nuli/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 1.10.0+cu113
Device count 1
/home/nuli/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/nuli/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Creating extension directory /home/nuli/.cache/torch_extensions/py38_cu113/gymtorch...
Emitting ninja build file /home/nuli/.cache/torch_extensions/py38_cu113/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF gymtorch.o.d -DTORCH_EXTENSION_NAME=gymtorch -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/nuli/anaconda3/envs/humanoid/lib/python3.8/site-packages/torch/include -isystem /home/nuli/anaconda3/envs/humanoid/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/nuli/anaconda3/envs/humanoid/lib/python3.8/site-packages/torch/include/TH -isystem /home/nuli/anaconda3/envs/humanoid/lib/python3.8/site-packages/torch/include/THC -isystem /home/nuli/anaconda3/envs/humanoid/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DTORCH_MAJOR=1 -DTORCH_MINOR=10 -c /home/nuli/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/src/gymtorch/gymtorch.cpp -o gymtorch.o 
[2/2] c++ gymtorch.o -shared -L/home/nuli/anaconda3/envs/humanoid/lib/python3.8/site-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o gymtorch.so
Loading extension module gymtorch...
2024-09-06 11:52:35,469 - INFO - logger - logger initialized
MOVING MOTION DATA TO GPU, USING CACHE: False
wandb: WARNING Disabling the wandb service is deprecated as of version 0.18.0 and will be removed in version 0.19.0.
Setting seed: 1
******************** Loading motion library ********************
Loading 1/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/144_20.npy
Delibnulitely not loading key body positions
Loading 2/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/02_05.npy
Delibnulitely not loading key body positions
Loading 3/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/91_05.npy
Delibnulitely not loading key body positions
Loading 4/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/104_41.npy
Delibnulitely not loading key body positions
Loading 5/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/141_22.npy
Delibnulitely not loading key body positions
Loading 6/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/41_10.npy
Delibnulitely not loading key body positions
Loading 7/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/32_07.npy
Delibnulitely not loading key body positions
Loading 8/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/38_03.npy
Delibnulitely not loading key body positions
Loading 9/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/90_31.npy
Delibnulitely not loading key body positions
Loading 10/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/81_18.npy
Delibnulitely not loading key body positions
Loading 11/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/80_40.npy
Delibnulitely not loading key body positions
Loading 12/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/61_12.npy
Delibnulitely not loading key body positions
Loading 13/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/18_02.npy
Delibnulitely not loading key body positions
Loading 14/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/23_08.npy
Delibnulitely not loading key body positions
Loading 15/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/21_11.npy
Delibnulitely not loading key body positions
Loading 16/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/15_08.npy
Delibnulitely not loading key body positions
Loading 17/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/14_26.npy
Delibnulitely not loading key body positions
Loading 18/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/141_16.npy
Delibnulitely not loading key body positions
Loading 19/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/08_11.npy
Delibnulitely not loading key body positions
Loading 20/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/08_07.npy
Delibnulitely not loading key body positions
Loading 21/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/16_36.npy
Delibnulitely not loading key body positions
Loading 22/22 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/13_20.npy
Delibnulitely not loading key body positions
Loaded 22 motions with a total length of 336.717s.
Traceback (most recent call last):
  File "train.py", line 72, in <module>
    train(args)
  File "train.py", line 65, in train
    env, env_cfg = task_registry.make_env(name=args.task, args=args)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/utils/task_registry.py", line 98, in make_env
    env = task_class(   cfg=env_cfg,
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic_view_motion.py", line 18, in __init__
    super().__init__(cfg, sim_params, physics_engine, sim_device, headless)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic_eval.py", line 12, in __init__
    super().__init__(cfg, sim_params, physics_engine, sim_device, headless)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 43, in __init__
    self.init_motions(cfg)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 118, in init_motions
    self._load_motion(motion_file, cfg.motion.no_keybody)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 157, in _load_motion
    self._motion_lib = MotionLib(motion_file=motion_file,
  File "/home/nuli/rl/expressive-humanoid/ASE/ase/utils/motion_lib.py", line 123, in __init__
    self.gts = torch.cat([m.global_translation for m in motions], dim=0).float().to(self._device)
  File "/home/nuli/rl/expressive-humanoid/ASE/ase/utils/motion_lib.py", line 123, in <listcomp>
    self.gts = torch.cat([m.global_translation for m in motions], dim=0).float().to(self._device)
  File "/home/nuli/rl/expressive-humanoid/ASE/ase/poselib/poselib/skeleton/skeleton3d.py", line 471, in global_translation
    self._global_translation = transform_translation(self.global_transformation)
  File "/home/nuli/rl/expressive-humanoid/ASE/ase/poselib/poselib/skeleton/skeleton3d.py", line 446, in global_transformation
    transform_mul(
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

nvrtc compilation failed: 

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_mul_mul_add_mu_2366695432019364975(float* tz1_3, float* tz2_3, float* ty1_3, float* ty2_3, float* tx1_3, float* tx2_3, float* tw1_3, float* tw2_3, float* aten_sub_5, float* aten_sub_2, float* aten_sub_1, float* aten_sub) {
{
if ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)<1135ll ? 1 : 0) {
    float tw1_3_1 = __ldg(tw1_3 + 98ll * ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)));
    float tz2_3_1 = __ldg(tz2_3 + 98ll * ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)));
    float tz1_3_1 = __ldg(tz1_3 + 98ll * ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)));
    float tw2_3_1 = __ldg(tw2_3 + 98ll * ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)));
    float tx1_3_1 = __ldg(tx1_3 + 98ll * ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)));
    float ty2_3_1 = __ldg(ty2_3 + 98ll * ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)));
    float ty1_3_1 = __ldg(ty1_3 + 98ll * ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)));
    float tx2_3_1 = __ldg(tx2_3 + 98ll * ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)));
    aten_sub[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = ((tw1_3_1 * tz2_3_1 + tz1_3_1 * tw2_3_1) + tx1_3_1 * ty2_3_1) - ty1_3_1 * tx2_3_1;
    aten_sub_1[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = ((tw1_3_1 * ty2_3_1 + ty1_3_1 * tw2_3_1) + tz1_3_1 * tx2_3_1) - tx1_3_1 * tz2_3_1;
    aten_sub_2[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = ((tw1_3_1 * tx2_3_1 + tx1_3_1 * tw2_3_1) + ty1_3_1 * tz2_3_1) - tz1_3_1 * ty2_3_1;
    aten_sub_5[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = ((tw1_3_1 * tw2_3_1 - tx1_3_1 * tx2_3_1) - ty1_3_1 * ty2_3_1) - tz1_3_1 * tz2_3_1;
  }}
}

**Comment by dbdxnuliba** [comment]
it has been solved by  pip install sentence_transformers
(humanoid) nuli@nuli~/rl/expressive-humanoid$ pip install sentence_transformers
